name: 'build and test'

# Rebuild on PRs and main branch changes
on:
  pull_request:
  push:
    branches:
      - main

env:
  IMAGEMAGICK_VERSION: 7.0.10-25

jobs:
  compile_artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build && npm run format && npm run lint && npm run package

      #use artifact when don't need to re-compile
      - id: download_artifact
        name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          # Optional, GitHub token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Required, workflow file name or ID
          workflow: build.yml
          workflow_conclusion: success
          # Optional, will use the branch
          #branch: main
          # Optional, will get head commit SHA
          # pr: ${{ github.event.pull_request.number }}
          # Optional, no need to specify if PR is
          # commit: ${{ github.event.pull_request.head.sha }}
          #commit: 64db9ad751c66a4ca568cef2e5426e2897d1ab3f
          # Required, uploaded artifact name
          name: ImageMagick-${{ env.IMAGEMAGICK_VERSION }}-x64-precompiled
          # Optional, directory where to extract artifact
          path: ../ImageMagick-${{ env.IMAGEMAGICK_VERSION }}-x64-precompiled

      - id: compiled_source
        uses: ./

        env:
          LDFLAGS: '-L/usr/local/lib -R/usr/local/lib'

        with:
          version: ${{ env.IMAGEMAGICK_VERSION }}
          # configure_args: '--with-modules'
          configure_args: '--with-modules --disable-installed'
          # skip_check: true
          skip_cache: true
          compile_fallback: true
          artifact_path: ../ImageMagick-${{ env.IMAGEMAGICK_VERSION }}-x64-precompiled

      - run: which -a convert
      - run: convert --version
      - run: identify -list configure
      - run: identify -list format

      - name: Convert a pdf into png
        run: convert -thumbnail 250x250 -background white -alpha remove -flatten ./test/sample.pdf thumbs.png

      - uses: actions/upload-artifact@v2
        with:
          name: ${{  steps.compiled_source.outputs.artifactName }}
          path: ${{  steps.compiled_source.outputs.artifactDir }}
          if-no-files-found: error

  test_artifact:
    runs-on: ubuntu-latest

    needs: [compile_artifact]

    steps:
      - uses: actions/checkout@v2

      - id: download_artifact
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ImageMagick-${{ env.IMAGEMAGICK_VERSION }}-x64-precompiled
          path: ../ImageMagick-${{ env.IMAGEMAGICK_VERSION }}-x64-precompiled

      - uses: ./
        with:
          version: ${{ env.IMAGEMAGICK_VERSION }}
          artifact_path: ${{ steps.download_artifact.outputs.download-path }}

      - run: which -a convert
      - run: convert --version
      - run: identify -list configure
      - run: identify -list format

      - name: Convert a pdf into png
        run: convert -thumbnail 250x250 -background white -alpha remove -flatten ./test/sample.pdf thumbs.png